### ISSUE TITLE
Test fails on ARM

### ISSUE THREAD

**Issue by petevine** [ekse/unicorn-rs#2]
```rust
$ RUST_BACKTRACE=1  target/debug/examples/test 
version : 1.0
Support for:
         x86: true
         arm: true
         mips: true
page size : 4096
thread '<main>' panicked at 'failed to query hardware mode: ARG', src/libcore/result.rs:746
stack backtrace:
   1: 0xb6f70eff - std::sys::backtrace::tracing::imp::write::hf68f1a220b61702c
                at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:40
   2: 0xb6f74443 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hb638acea7c29901b
                at src/libstd/panicking.rs:178
   3: 0xb6f73b13 - std::panicking::default_hook::h508c3dab3df347d6
                at src/libstd/panicking.rs:193
   4: 0xb6f6d84b - std::panicking::on_panic::h3a6e649f33b132c3
                at src/libstd/panicking.rs:227
   5: 0xb6f4fd6b - std::sys_common::unwind::begin_unwind_inner::h17f9e42de6d55309
                at src/libstd/sys/common/unwind/mod.rs:237
   6: 0xb6f526bb - std::sys_common::unwind::begin_unwind_fmt::h039d18bd8498e1d0
                at src/libstd/sys/common/unwind/mod.rs:202
   7: 0xb6f6d21b - rust_begin_unwind
                at src/libstd/sys/common/unwind/mod.rs:179
   8: 0xb6f814a7 - core::panicking::panic_fmt::h813eaa27a5810609
                at src/libcore/panicking.rs:69
   9: 0xb6f46fa7 - core::result::unwrap_failed::h419bc270f6772dcb
                at src/libcore/macros.rs:29
  10: 0xb6f47117 - _<std..result..Result<T, E>>::expect::he67c7df582d2e1e0
                at src/libcore/result.rs:708
  11: 0xb6f4673f - test::main::h1ef728500ff2f89b
                at examples/test.rs:17
  12: 0xb6f73323 - fn()::fn_pointer_shim.32839::ha52fbbed76ed0ca0
  13: 0xb6f73127 - std::panic::recover::_$u7b$$u7b$closure$u7d$$u7d$::he74338885f2bd0e2
                at src/libstd/panic.rs:318
  14: 0xb6f730f7 - std::sys_common::unwind::try::try_fn::h0f540c0db5f980f7
                at src/libstd/sys/common/unwind/mod.rs:127
````
`rustc 1.9.0-dev (470ca1c3f 2016-04-07)`

**Comment by ekse** [comment]
Oops, I modified this file while I was adding the Cpu structs and forgot to set back the emulator to CpuARM. It should be working now. Thanks for reporting.

**Comment by petevine** [comment]
ARM coincidentally :)

Now I'm getting en error from unicorn:

````
page size : 1024
hardware mode : 16
Sample error message : Invalid hook type (UC_ERR_HOOK)
Regions : 2
MemRegion { begin: 65536, end: 81919, perms: PROT_READ | PROT_WRITE | PROT_EXEC | PROT_ALL }
MemRegion { begin: 131072, end: 147455, perms: PROT_READ | PROT_WRITE | PROT_EXEC | PROT_ALL }
````

**Comment by petevine** [comment]
BTW, are you seeing this warning?

```rust
src/ffi.rs:37:36: 37:59 warning: found non-foreign-function-safe member in struct marked #[repr(C)]: found struct without foreign-function-safe representation annotation in foreign module, consider adding a #[repr(C)] attribute to the type, #[warn(improper_ctypes)] on by default
src/ffi.rs:37                           regions: *const *const MemRegion,
````

**Comment by ekse** [comment]
The error message is expected, it's to test the unicorn function error_msg() ;-)

As for the warning I do see it but I don't really know how to make it go away. MemRegion is repr(C), I tried creating a type for `*const *const MemRegion` but if I try to make it repr(C) I get the error message "attribute should be applied to struct or enum".

**Comment by petevine** [comment]
Ah, ok! The other test passes too.
